### ISSUE TITLE
This happens when you run Route List in Laravel

### ISSUE THREAD

**Issue by shadracnicholas** [osenco/mpesa#2]
![Screenshot 2020-04-01 at 18 44 18](https://user-images.githubusercontent.com/46599542/78157610-d3e9be80-7448-11ea-9968-ee79bc77814a.png)

**Comment by maukoese** [comment]
Hi,

This is because $_SERVER/ server environment is not set when you run commands in the terminal. I'm updating it to do a check for that first. Thanks.

**Comment by maukoese** [comment]
This has been fixed. Check the latest release.
