### ISSUE TITLE
Composer Autoload Deprecation Notice

### ISSUE THREAD

**Issue by shadracnicholas** [osenco/mpesa#3]
Update classes to comply with pr-4 autoloading standard

Deprecation Notice: Class Osen\Mpesa\C2B located in ./vendor/osenco/mpesa/src/C2B.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Osen\Mpesa\Service located in ./vendor/osenco/mpesa/src/Service.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Osen\Mpesa\B2B located in ./vendor/osenco/mpesa/src/B2B.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Osen\Mpesa\B2C located in ./vendor/osenco/mpesa/src/B2C.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Osen\Mpesa\STK located in ./vendor/osenco/mpesa/src/STK.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by maukoese** [comment]
Hey,
I changed to PSR-4,
Doing a release in a few.

**Comment by maukoese** [comment]
v1.20.6 should take care of this.
