### ISSUE TITLE
B2B file

### ISSUE THREAD

**Issue by thothopat** [osenco/mpesa#5]
Line 58 of B2B file, passing more parameters on remote_post expecting 2 parameters, 3 sent.
removing token worked as it gets fetched under remote_post function
Got me the whole day trying to figure it out

**Comment by maukoese** [comment]
Does B2B still work for you?

**Comment by thothopat** [comment]
yes, it works.
I had to generate SecurityCredential from daraja app to use it. Either the certificate is no longer supported or safaricom has new certificate under the daraja that supports it. This is under the sandbox test

**Comment by maukoese** [comment]
Thank you. I'll fix it. Though Saf doesn't allow new B2B integrations.
